# Generated by Django 5.0.14 on 2025-08-17 22:18

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
                ('custom_id', models.CharField(blank=True, default='00000000', max_length=8, unique=True, verbose_name='グループID')),
                ('icon', models.ImageField(blank=True, default='default_images/702.png', upload_to='group_icon_path', verbose_name='グループアイコン')),
                ('is_locked', models.BooleanField(default=False, verbose_name='ロック機能')),
                ('is_approval', models.BooleanField(default=False, verbose_name='承認機能')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to=settings.AUTH_USER_MODEL, verbose_name='グループ作成者')),
                ('users', models.ManyToManyField(related_name='user_groups', to=settings.AUTH_USER_MODEL, verbose_name='グループメンバー')),
            ],
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='依頼日時')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysfa.group', verbose_name='グループ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='依頼ユーザー')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(error_messages={'blank': '商品名を入力してください'}, max_length=50, verbose_name='商品名')),
                ('customer_category', models.CharField(error_messages={'blank': '顧客カテゴリを入力してください'}, max_length=50, verbose_name='顧客カテゴリ')),
                ('contents', models.TextField(error_messages={'max_length': '100文字以内で入力してください'}, max_length=100, verbose_name='投稿文')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='グループ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
