# Generated by Django 5.0.14 on 2025-08-17 22:37

import random

from django.db import migrations


def generate_custom_id_for_existing_groups(apps, schema_editor):
    Group = apps.get_model('mysfa', 'Group')
    
    for group in Group.objects.all():
        if not group.custom_id or group.custom_id == '00000000':
            # 8桁のランダムな数字を生成
            while True:
                new_id = ''.join([str(random.randint(0, 9)) for _ in range(8)])
                if not Group.objects.filter(custom_id=new_id).exists():
                    group.custom_id = new_id
                    group.save()
                    break


def reverse_generate_custom_id_for_existing_groups(apps, schema_editor):
    # この操作は元に戻せないため、何もしない
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('mysfa', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            generate_custom_id_for_existing_groups,
            reverse_generate_custom_id_for_existing_groups
        ),
    ]
