# Generated by Django 5.2 on 2025-08-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysfa', '0002_auto_20250817_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinrequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/', verbose_name='投稿画像'),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/', verbose_name='投稿画像'),
        ),
        migrations.AlterField(
            model_name='group',
            name='icon',
            field=models.ImageField(blank=True, default='default_images/702.png', null=True, upload_to='group_icon_path', verbose_name='グループアイコン'),
        ),
    ]
