# Generated by Django 5.2 on 2025-08-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysfa', '0003_joinrequest_image_post_image_alter_group_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinrequest',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='likes_count',
            field=models.IntegerField(default=0, verbose_name='いいね数'),
        ),
    ]
