FROM python:3.12-slim

RUN apt-get update && apt-get install -y \
    bash \
    procps \
    gcc \
    pkg-config \
    default-libmysqlclient-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY src/ .

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]