# Generated by Django 5.2 on 2025-08-24 19:49

from django.db import migrations, models

import accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='default_images/ic013.png', null=True, upload_to=accounts.models.CustomUser.user_profile_image_path),
        ),
    ]
