name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    # SQLiteを使用するため、MySQLサービスは不要

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run linters
      run: |
        flake8 src/ --max-line-length=88 --ignore=E203,W503
        black --check src/ --line-length 88
        isort --check-only src/ --profile black
    
    - name: Run tests
      env:
        SECRET_KEY: test-secret-key
        DEBUG: True
        ALLOWED_HOSTS: localhost,127.0.0.1
      run: |
        cd src
        python manage.py migrate
        python manage.py test

  # DockerHubへのプッシュは不要（EC2で直接ビルド）
