jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        ...
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || { echo "requirements.txtインストール失敗"; exit 1; }

      - name: Run linters
        run: |
          flake8 src/ --max-line-length=88 --ignore=E203,W503
          black --check src/ --line-length 88
          isort --check-only src/ --profile black

      - name: MySQL container logs
        run: |
          docker ps -a
          docker logs $(docker ps -q --filter "ancestor=mysql:8.0")

      - name: Check MySQL connection
        run: |
          mysql -h 127.0.0.1 -utest_user -ptest_pass -e "SHOW DATABASES;" || { echo "MySQL接続失敗"; exit 1; }

      - name: Wait for MySQL to be ready
        run: |
          for i in {30..0}; do
            if mysqladmin ping -h127.0.0.1 -ptest_pass --silent; then
              echo "MySQL is up!"
              break
            fi
            echo "Waiting for MySQL..."
            sleep 2
          done

      - name: Run tests
        env: ...
        run: |
          cd src
          python manage.py migrate || { echo "migrate失敗"; exit 1; }
          python manage.py test --verbosity=2 | tee test-results.log || { echo "テスト失敗"; exit 1; }

      - name: Output test results
        if: failure()
        run: cat src/test-results.log || echo "test-results.logがありません"

      - name: Dump environment
        if: failure()
        run: |
          env
          docker ps -a
          netstat -an
